- hosts: localhost
  become: yes
  tasks:
    - name: Create ssl dir
      command: mkdir /etc/contrail/ssl

- hosts: 192.168.7.29
  become: yes
  tasks:
    - name: find files to copy
      find: 
        paths: "/etc/contrail/ssl"
        recurse: yes 
        patterns: "*.pem"
      register: files_to_copy

    - name: Copy files
      fetch: 
        src: '{{ item.path }}'
        dest: /etc/contrail/ssl/
        flat: yes
      with_items: "{{ files_to_copy.files }}"

- hosts: localhost
  become: yes
  tasks:
    - name: Move certs to ssl dir
      command: "{{item}}"
      with_items:
        - mkdir /etc/contrail/ssl/certs
        - mkdir /etc/contrail/ssl/private
        - mv /etc/contrail/ssl/server.pem /etc/contrail/ssl/certs
        - mv /etc/contrail/ssl/ca-cert.pem /etc/contrail/ssl/certs
        - mv /etc/contrail/ssl/server-privkey.pem /etc/contrail/ssl/private
