- hosts: all_nodes
  become: yes
  tasks:
    - name: Enable Password Authentication and PermitRootLogin
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '{{item.From}}'
        line: '{{item.To}}'
      with_items:
        - { From: 'PasswordAuthentication no', To: 'PasswordAuthentication yes'}
        - { From: '#PermitRootLogin prohibit-password', To: 'PermitRootLogin yes'}
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
    - name: Change root password
      user: 
        name: root
        password: "{{ 'c0ntrail123' | password_hash('sha512') }}"
    - name: Allow root user to login
      replace:
        path: /root/.ssh/authorized_keys
        regexp: 'ssh-rsa.*'
        replace: 'ssh-rsa'
