- hosts: 192.168.7.29
  become: yes
  tasks:
    - name: Enable snat in default namespace
      shell: kubectl get ns default -o yaml > default.yaml && sed -i '/metadata:/a\  annotations:\n    opencontrail.org/ip_fabric_snat:\ "true"' default.yaml && kubectl replace -f default.yaml
    - name: Set keystone context
      command: "{{item}}"
      with_items:
        - snap install kubectl --classic
        - snap install client-keystone-auth --edge
        - kubectl config set-context keystone --user=keystone-user
        - kubectl config use-context keystone
        - kubectl config set-credentials keystone-user --exec-command=/snap/bin/client-keystone-auth
        - kubectl config set-credentials keystone-user --exec-api-version=client.authentication.k8s.io/v1beta1
    - name: Set juju-cluster for keystone context
      replace:
        path: /root/.kube/config
        regexp: 'cluster: \"\"'
        replace: 'cluster: juju-cluster'