- hosts: localhost
  become: yes
  tasks:
    - name: Create ssl dir
      file:
        path: /etc/contrail/ssl
        state: directory
        mode: '0755'

- hosts: 192.168.7.29
  become: yes
  tasks:
    - name: find files to copy
      find: 
        paths: "/etc/contrail/ssl"
        recurse: yes 
        patterns: "*.pem"
      register: files_to_copy

    - name: Copy files
      fetch: 
        src: '{{ item.path }}'
        dest: /etc/contrail/ssl/
        flat: yes
      with_items: "{{ files_to_copy.files }}"

- hosts: localhost
  become: yes
  tasks:
    - name: Create certs and private dir
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      with_items:
        - /etc/contrail/ssl/certs
        - /etc/contrail/ssl/private
    - name: Move certs to ssl dir
      command: "{{item}}"
      with_items:
        - mv /etc/contrail/ssl/server.pem /etc/contrail/ssl/certs
        - mv /etc/contrail/ssl/ca-cert.pem /etc/contrail/ssl/certs
        - mv /etc/contrail/ssl/server-privkey.pem /etc/contrail/ssl/private
    - name: Add password to controller
      lineinfile:
        path: /root/.local/share/juju/accounts.yaml
        insertafter: 'user: admin'
        line: "    password: c0ntrail123"
        state: 'present'
